Tooltip: Tooltip
Dependencies: Dependencies
PercentComplete: Percent complete
Duration: Duration
EndDate: End date
StartDate: Start date
TaskName: Task name
TaskId: Task ID
JSGantt: JSGantt
Google: Google
Gantt: Gantt
Chart: Chart
Action: Action
Timestamp: Timestamp
NoTaskLogsYet: There are no tasks logs yet
TaskLogs: Logs
OverdueTasks: Overdue tasks
OngoingTasks: Ongoing tasks
CompletedTasks: Completed tasks 
ProjectDuration: Project duration
RemainingEffort: Remaining effort
ActualEffort: Actual effort
PlannedEffort: Planned effort
TotalActualEffort: Total actual effort
TotalPlannedEffort: Total planned effort
DegreeOfCompletion: Degree of completion
ProjectStatus: Project status
ActualDurationHours: Actual duration
ActualEffortHours: Actual effort
Hours: Hours
DurationHours: Duration
EffortHours: Effort
CompletionPercentage: Completion percentage
Monitoring: Monitoring
UpdateHistory: Update history
TaskStatusChange target@Text: Task status change:  "#{target}"
TaskStateTransition source@Text target@Text: Task status transition: "#{source}" -> "#{target}"
Remarks: Remarks
TaskUncompleted: Task uncompleted
RestartTask: Restart task
ResumeTask: Resume task
CompleteTask: Complete task
PauseTask: Pause task
StartTask: Start task
StateMachineDiagram: State machine diagram 
TaskStatusStateTransition: State transition for task status
BasicEntities: Basic entities
TaskStatusPaused: Paused
PartiallyCompleted: Partially completed
MarkTaskAsPartiallyCompleted: Mark task as partially completed
NotCompleted: Not completed
MarkTaskAsNotCompleted: Mark task as not completed
CompleteTheTask: Complete the task
MarkTaskAsComplete: Mark task as complete
You: You
NoTasksToManageYet: There are no tasks to manage yet
NotAuthorized: Not authorized
LoginToAccessPlease: Please login to access this page
TaskManagement: Task Management
NoDescriptionGiven: No description given
TotalTasks: Total tasks
TotalProjects: Total projects
NoTasksWereFoundForSearchTerms: No tasks were found containing all your search terms
Deadline: Deadline
CompletionDate: Completion date
LoginToCheckYourTasks: Please log in to check your tasks
MyTasks: My tasks
Statistics: Statistics
NoTasksYet: There are no tasks yet
OwnerNotAssigned: Owner not assigned
FirstTaskInSequence: This is the first task in the sequence
PreviousTask: Previous task
Owner: Owner
TaskOwner: Task owner
Team: Team
ManagerNotAssigned: Manager not assigned
Manager: Manager
NotAppointedYet: Not appointed yet
ProjectManager: Project manager
AppointmentDate: Appointment date
JobTitle: Job title
NoEmployeesInThisDepartmentYet: There are no employees in this department yet
NoEmployeesYet: There are no employees yet
Employee: Employee
Employees: Employees
Sequence: Sequence
TaskStatus: Status
TaskStatusPartiallyCompleted: Partially completed
TaskStatusUncompleted: Uncompleted
TaskStatusCompleted: Completed
TaskStatusInProgress: In progress
TaskStatusNotStarted: Not started
TaskStatusNew: New
ParentTask: Parent task
NoSubtasksYet: There are no subtasks yet
NoTasksForThisProjectYet: There are no tasks for this project yet
End: End
Start: Start
ProjectEnd: Project end
ProjectStart: Project start
ProjectStatistics: Project statistics
ShowProjects: Show projects
LoginForMoreDetailsPlease: Please login for more details
NumberOfTasks: Number of tasks
NumberOfProjects: Number of projects
WelcomeTo: Welcome to
NoOutletsYet: There are no outlet types yet
OutletTypes: Outlet types
OutletType: Outlet type
Location: Location
NoProjectsYet: There are no projects yet
Subtasks: Subtasks
Task: Task
Tasks: Tasks
Project: Project
Projects: Projects
RootDepartment: Root department
NoDivisionsInDepartment: There are no divisions in this department
ParentDepartment: Parent department
Properties: Properties
Code: Code
Divisions: Divisions
Department: Department
Departments: Departments
Planning: Planning
ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found

PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: OpenPlan