DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found

PleaseAddIfNecessary: Please add if necessary
NoPagesOnThisSiteYet: There are no pages on this site yet
Empty: Empty
Favicon: Favicon
Copy: Copy
Settings: Settings
Color: Color
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
EmptyPage: Empty page
NumberOfPages: number of pages
Create: Create
YouCanAddSomeFromProductList: You can add some from the product list
NoProductsAssignedYet: There are currently no products assigned to this page
AddProduct: Add product
Layout: Layout
Cards: Cards
List: List
Table: Table
BackgroundColor: Background color
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Rating: Rating
Currency: Currency
Price: Price
Item: Item
Items: Items
Article: Article
Articles: Articles
Url: URL
Contents: Contents
ContentType: Content type
Level: Level
HeadingLevel: Heading level
Html: HTML
Text: Text
Headings: Headings
Heading: Heading
Preview: Preview
Headers: Headers
Details: Details
Title: Title
Header: Header
Body: Body
Footer: Footer
Page: Page
Pages: Pages
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
Site: Site
Sites: Sites
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: OpenPlan