
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена

PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
NoPagesOnThisSiteYet: На этом сайте пока нет страниц
Empty: Пустой
Favicon: Фавикон
Copy: Копировать
Settings: Настройки
Color: Цвет
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
EmptyPage: Пустая страница
NumberOfPages: кол. страниц
Create: Создать
YouCanAddSomeFromProductList: Вы можете добавить некоторые из списка товаров
NoProductsAssignedYet: В настоящее время на этой странице нет ни одного продукта
AddProduct: Добавить продукт
Layout: Макет
Cards: Карты
List: Список
Table: Таблица
BackgroundColor: Цвет фона
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Rating: Рейтинг
Currency: Валюта
Price: Цена
Item: Продукт
Items: Продукты
Article: Товар
Articles: Товары
Url: URL-адрес
Contents: Содержание
ContentType: Тип содержимого
Level: Уровень
HeadingLevel: Уровень заголовка
Html: HTML
Text: Текст
Headings: Рубрики
Heading: Рубрика
Preview: Предварительный просмотр
Headers: Заголовки
Details: Подробности
Title: Название
Header: Заголовок
Body: Тело
Footer: Нижний колонтитул
Page: Страница
Pages: Страницы
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
Site: Сайт
Sites: Сайты
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
AppName: ТТ