ActualDurationHours: Фактическая продолжительность
ActualEffortHours: Фактические трудозатраты
Hours: Часы
DurationHours: Продолжительность
EffortHours: Трудозатраты
CompletionPercentage: Процент выполнения
Monitoring: Мониторинг
UpdateHistory: История обновлений
TaskStatusChange target: Изменение статуса задачи: "#{target}"
TaskStateTransition source target: Переход статуса задачи: #{source} -> #{target}
Remarks: Замечания
TaskUncompleted: Задача не выполнена
RestartTask: Перезапустить задачу
ResumeTask: Возобновить задачу
CompleteTask: Завершить задачу
PauseTask: Приостановить задачу
StartTask: Начать задачу
StateMachineDiagram: Схема машины состояний
TaskStatusStateTransition: Переход состояния для статуса задачи
BasicEntities: Базовые сущности
TaskStatusPaused: Приостановлено
PartiallyCompleted: Частично выполнено
MarkTaskAsPartiallyCompleted: Отметить задачу как частично выполненную
NotCompleted: Не выполнена
MarkTaskAsNotCompleted: Отметить задачу как невыполненную
CompleteTheTask: Завершить задачу
MarkTaskAsComplete: Отметить задачу как выполненную
You: Вы
NoTasksToManageYet: Пока нет задач для управления
NotAuthorized: Не разрешено
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
TaskManagement: Управление задачами
NoDescriptionGiven: Описание не предоставлено
TotalTasks: Всего задач
TotalProjects: Всего проектов
NoTasksWereFoundForSearchTerms: Не найдено ни одной задачи, содержащей все ваши условия поиска
Deadline: Крайний срок
CompletionDate: Срок выполнения
LoginToCheckYourTasks: Пожалуйста, войдите в систему, чтобы проверить свои задачи
MyTasks: Мои задачи
Statistics: Статистика
NoTasksYet: Задач пока нет
OwnerNotAssigned: Владелец не назначен
FirstTaskInSequence: Это первая задача в последовательности
PreviousTask: Предыдущая задача
Owner: Владелец
TaskOwner: Владелец задачи
Team: Команда
ManagerNotAssigned: Руководитель не назначен
Manager: Руководитель
NotAppointedYet: Пока не назначен
ProjectManager: Руководитель проекта
AppointmentDate: Дата назначения
JobTitle: Должность
NoEmployeesInThisDepartmentYet: В этом отделе пока нет сотрудников
NoEmployeesYet: Сотрудников пока нет
Employee: Сотрудник
Employees: Сотрудники
Sequence: Последовательностьx
TaskStatus: Статус
TaskStatusPartiallyCompleted: Частично выполнено
TaskStatusUncompleted: Невыполнено
TaskStatusCompleted: Выполнено
TaskStatusInProgress: Выполняется
TaskStatusNotStarted: Не запущено
TaskStatusNew: Новое
ParentTask: Родительская задача
NoSubtasksYet: Подзадач пока нет
NoTasksForThisProjectYet: Для этого проекта пока нет задач
End: Конец
Start: Начало
ProjectEnd: Конец проекта
ProjectStart: Начало проекта
ProjectStatistics: Статистика проектов
ShowProjects: Показать проекты
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
NumberOfTasks: Количество задач
NumberOfProjects: Количество проектов
WelcomeTo: Добро пожаловать на
NoOutletsYet: Типов точек пока нет
OutletTypes: Типы точек
OutletType: Тип точки
Location: Локация
NoProjectsYet: Проектов пока нет
Subtasks: Подзадачи
Task: Задача
Tasks: Задачи
Project: Проек
Projects: Проекты
RootDepartment: Корневой отдел
NoDivisionsInDepartment: В этом департаменте нет подразделений
ParentDepartment: Родительский отдел
Properties: Свойства
Code: Код
Divisions: Отделы
Department: Департамент
Departments: Департаменты
Planning: Планирование
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена

PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
AppName: OpenPlan